# Generated by Django 5.0.3 on 2024-03-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_author'),
        ('user', '0003_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
