# Generated by Django 5.0.3 on 2024-03-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_author'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog_ids',
            field=models.ManyToManyField(to='blog.blog'),
        ),
    ]
