# Generated by Django 5.0.3 on 2024-03-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_blog_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
